---
- name: Setup local machine
  hosts: macbook-pro
  become: false
  roles:
    - { role: macos, tags: [macos] }
    - { role: homebrew, tags: [homebrew, brew] }
    - { role: java, tags: [java] }
    - { role: dotfiles, tags: [dotfiles] }
    - { role: projects, tags: [projects] }
