---
- name: Create .config directory
  file:
    dest: "{{ lookup('env', 'HOME') }}/.config"
    state: directory

- name: Copy dotfiles
  file:
    src: "{{ role_path }}/files/{{ item.src }}"
    dest: "{{ lookup('env', 'HOME') }}/.{{ item.dest | default(item.src) }}"
    state: link
    force: yes
  with_items: "{{ dotfiles }}"

- name: Change default shell
  command: chsh -s {{ default_shell }}
  when: lookup('env', 'SHELL') != default_shell

