---
- name: Create projects directory
  file:
    dest: "{{ projects_dir }}"
    state: directory

- name: Clone projects
  vars:
    default_dest: "{{projects_dir}}/{{item.repo | basename | splitext | first}}"
  git:
    repo: "{{ item.repo }}"
    dest: "{{ item.dest | default(default_dest) }}"
    version: "{{ item.version }}"
  with_items: "{{ git_repos }}"
