---
- name: Setup additional homebrew taps
  community.general.homebrew_tap:
    name: "{{ homebrew_taps }}"
    state: present

- name: Install packages via Homebrew
  community.general.homebrew:
    name: "{{ homebrew_formulas }}"
    state: present
    update_homebrew: false

- name: Install casks via Homebrew
  community.general.homebrew_cask:
    name: "{{ homebrew_casks }}"
    state: present
