---
- name: Setup additional homebrew taps
  community.general.homebrew_tap:
    name: "{{ item }}"
    state: present
  with_items: "{{ homebrew_taps }}"

- name: Install packages via Homebrew
  community.general.homebrew:
    name: "{{ item }}"
    state: present
    update_homebrew: true
  with_items: "{{ homebrew_formulas }}"

- name: Install casks via Homebrew
  community.general.homebrew_cask:
    name: "{{ item }}"
    state: present
  with_items: "{{ homebrew_casks }}"
