---
- name: Create projects directory
  file:
    dest: "{{ projects_dir }}"
    state: directory

- name: Setup projects
  vars:
    project_dir: "{{ git_repo.repo | basename | splitext | first }}"
    default_dest: "{{projects_dir}}/{{ project_dir }}"
  include_tasks: git_projects.yml
  loop: "{{ git_repos }}"
  loop_control:
    label: "{{ git_repo.repo }}"
    loop_var: git_repo
