---
default_shell: "{{ homebrew_prefix }}/bin/zsh"

homebrew_formulas:
  - awscli
  - colima
  - docker
  - docker-credential-helper
  - fzf
  - gpgme
  - jq
  - node@18
  - pandoc
  - pass
  - pwgen
  - ripgrep
  - tmux
  - vim
  - wget
  - ykman
  - zsh

homebrew_taps:
  - homebrew/cask

homebrew_casks:
  - alacritty
  - basictex
  - font-jetbrains-mono
  - font-jetbrains-mono-nerd-font
  - hashicorp-vagrant
  - little-snitch
  - macfuse
  - micro-snitch
  - rectangle
  - tex-live-utility
  - veracrypt
  - virtualbox

dotfiles:
  files:
    - { dest: config, state: directory }
    - { dest: config/alacritty, state: directory }
  links:
    - { src: alacritty/themes, dest: config/alacritty/themes }
    - { src: gitignore_global }
    - { src: ideavimrc }
    - { src: tmux-statusline.conf }
    - { src: vim }
  templates:
    - { src: alacritty.toml, dest: config/alacritty/alacritty.toml }
    - { src: gitconfig }
    - { src: tmux.conf }
    - { src: vimrc }
    - { src: zshrc }
    - { src: dotf.zsh, dest: oh-my-zsh/custom/dotf.zsh }

git:
  user:
    name: lakhak
    email: lakhak@users.noreply.github.com
    signingkey: 2D8E01D473210CCB!

sdkman_sdks:
  - { sdk: java, version: 8.0.382-tem }
  - { sdk: java, version: 11.0.21-tem }
  - { sdk: java, version: 17.0.8-tem }
  - { sdk: java, version: 21-tem }
  - { sdk: maven, version: 3.6.3 }
  - { sdk: sbt, version: 1.4.7 }
  - { sdk: visualvm, version: 2.1.2 }
