---
homebrew_formulas:
  - awscli
  - fuse-t
  - fzf
  - git # replace apple xcode git
  - gnupg
  - hashicorp/tap/hashicorp-vagrant
  - jq
  - node@22
  - pandoc
  - pass
  - pinentry-mac
  - ripgrep
  - tmux
  - vim
  - wget
  - ykman

homebrew_taps:
  - hashicorp/tap
  - macos-fuse-t/cask

homebrew_casks:
  - alacritty
  # - basictex
  - font-jetbrains-mono
  - font-jetbrains-mono-nerd-font
  - little-snitch
  - micro-snitch
  - podman-desktop
  - rectangle
  # - tex-live-utility
  - veracrypt-fuse-t
  # - virtualbox
